name: quiz_app
description: A Flutter application for a quiz.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_countdown_timer: ^4.1.0
  flutter_rating_bar: ^4.0.1
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/quiz_data.json
    - assets/ideas.png
    - assets/success_sound.mp3
    - assets/wrong_sound.mp3
  uses-material-design: true
